In [1]:
# Importing necesary packages
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

In [2]:
# importing the datset
c_data = pd.read_csv("crime_data.csv")
c_data.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [3]:
c_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  50 non-null     object 
 1   Murder      50 non-null     float64
 2   Assault     50 non-null     int64  
 3   UrbanPop    50 non-null     int64  
 4   Rape        50 non-null     float64
dtypes: float64(2), int64(2), object(1)
memory usage: 2.1+ KB


In [4]:
# removing first column because it's just an name identifier
data = c_data.iloc[:,1:5]
data.head()

Murder  Assault  UrbanPop  Rape
0    13.2      236        58  21.2
1    10.0      263        48  44.5
2     8.1      294        80  31.0
3     8.8      190        50  19.5
4     9.0      276        91  40.6

In [5]:
# checking for null values 
std_df = StandardScaler().fit_transform(data)
std_df

array([[ 1.25517927,  0.79078716, -0.52619514, -0.00345116],
       [ 0.51301858,  1.11805959, -1.22406668,  2.50942392],
       [ 0.07236067,  1.49381682,  1.00912225,  1.05346626],
       [ 0.23470832,  0.23321191, -1.08449238, -0.18679398],
       [ 0.28109336,  1.2756352 ,  1.77678094,  2.08881393],
       [ 0.02597562,  0.40290872,  0.86954794,  1.88390137],
       [-1.04088037, -0.73648418,  0.79976079, -1.09272319],
       [-0.43787481,  0.81502956,  0.45082502, -0.58583422],
       [ 1.76541475,  1.99078607,  1.00912225,  1.1505301 ],
       [ 2.22926518,  0.48775713, -0.38662083,  0.49265293],
       [-0.57702994, -1.51224105,  1.21848371, -0.11129987],
       [-1.20322802, -0.61527217, -0.80534376, -0.75839217],
       [ 0.60578867,  0.94836277,  1.21848371,  0.29852525],
       [-0.13637203, -0.70012057, -0.03768506, -0.0250209 ],
       [-1.29599811, -1.39102904, -0.5959823 , -1.07115345],
       [-0.41468229, -0.67587817,  0.03210209, -0.34856705],
       [ 0.44344101, -0.

# Model Building or Creating a clusters

In [6]:
dbscan = DBSCAN(eps = 1, min_samples = 4)
dbscan.fit(std_df)

DBSCAN(eps=1, min_samples=4)

In [7]:
dbscan.labels_

array([ 0, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,
        0,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  0,  1,  0, -1,  1,  1,  1,  1,  1,  1,  1],
      dtype=int64)

In [8]:
# assigning clusterid to data set
c_data['cluser_id'] = dbscan.labels_

In [9]:
c_data.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape  cluser_id
0     Alabama    13.2      236        58  21.2          0
1      Alaska    10.0      263        48  44.5         -1
2     Arizona     8.1      294        80  31.0         -1
3    Arkansas     8.8      190        50  19.5         -1
4  California     9.0      276        91  40.6         -1

In [10]:
# clusters value counts
c_data['cluser_id'].value_counts()

 1    28
-1    18
 0     4
Name: cluser_id, dtype: int64

In [11]:
# grouping clusters using clustersid
c_data.groupby('cluser_id').agg(['mean'])

Murder     Assault   UrbanPop       Rape
                mean        mean       mean       mean
cluser_id                                             
-1         11.005556  247.166667  70.666667  28.766667
 0         14.050000  238.000000  57.750000  23.200000
 1          4.825000  112.035714  63.357143  16.107143

In [12]:
c_data[c_data.cluser_id == -1]

Unnamed: 0  Murder  Assault  UrbanPop  Rape  cluser_id
1           Alaska    10.0      263        48  44.5         -1
2          Arizona     8.1      294        80  31.0         -1
3         Arkansas     8.8      190        50  19.5         -1
4       California     9.0      276        91  40.6         -1
5         Colorado     7.9      204        78  38.7         -1
7         Delaware     5.9      238        72  15.8         -1
8          Florida    15.4      335        80  31.9         -1
9          Georgia    17.4      211        60  25.8         -1
10          Hawaii     5.3       46        83  20.2         -1
12        Illinois    10.4      249        83  24.0         -1
19        Maryland    11.3      300        67  27.8         -1
21        Michigan    12.1      255        74  35.1         -1
23     Mississippi    16.1      259        44  17.1         -1
27          Nevada    12.2      252        81  46.0         -1
30      New Mexico    11.4      285        70  32.1         -1
31        New York    11.1      254        86  26.1         -1
32  North Carolina    13.0      337        45  16.1         -1
42           Texas    12.7      201        80  25.5         -1

# Airlines 

In [13]:
airlines = pd.read_csv("EastWestAirlines.csv")
airlines.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [14]:
# removing the first column which is only a identifier
airlines2 = airlines.iloc[:,1:]
airlines2.head()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    28143           0          1          1          1          174   
1    19244           0          1          1          1          215   
2    41354           0          1          1          1         4123   
3    14776           0          1          1          1          500   
4    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [15]:
# cheking for nul-VALUES AND column types
airlines2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Balance            3999 non-null   int64
 1   Qual_miles         3999 non-null   int64
 2   cc1_miles          3999 non-null   int64
 3   cc2_miles          3999 non-null   int64
 4   cc3_miles          3999 non-null   int64
 5   Bonus_miles        3999 non-null   int64
 6   Bonus_trans        3999 non-null   int64
 7   Flight_miles_12mo  3999 non-null   int64
 8   Flight_trans_12    3999 non-null   int64
 9   Days_since_enroll  3999 non-null   int64
 10  Award?             3999 non-null   int64
dtypes: int64(11)
memory usage: 343.8 KB


In [16]:
# standardizing the data 
airlines_norm = StandardScaler().fit_transform(airlines2)
airlines_norm

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.39545434e+00, -7.66919299e-01],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.37995704e+00, -7.66919299e-01],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.41192021e+00, -7.66919299e-01],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -3.62167870e-01, -1.31560393e+00,  1.30391816e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -9.85033311e-02, -1.31608822e+00, -7.66919299e-01],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01, -1.31754109e+00, -7.66919299e-01]])

In [24]:
# Creating clusters
airlines_c = DBSCAN(eps = 1, min_samples = 6)
airlines_c.fit(airlines_norm)

DBSCAN(eps=1, min_samples=6)

In [29]:
print(airlines_c.labels_)

[0 0 0 ... 1 0 0]


In [31]:
# assigning clustersid to dataset
airlines2['cluser_id'] = airlines_c.labels_
airlines2

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0       28143           0          1          1          1          174   
1       19244           0          1          1          1          215   
2       41354           0          1          1          1         4123   
3       14776           0          1          1          1          500   
4       97752           0          4          1          1        43300   
...       ...         ...        ...        ...        ...          ...   
3994    18476           0          1          1          1         8525   
3995    64385           0          1          1          1          981   
3996    73597           0          3          1          1        25447   
3997    54899           0          1          1          1          500   
3998     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  cluser_id  
0          0          0  
1          0          0  
2          0          0  
3          0          0  
4          1          1  
...      ...        ...  
3994       1          1  
3995       1          1  
3996       1          1  
3997       0          0  
3998       0          0  

[3999 rows x 12 columns]

In [27]:
airlines2['cluser_id'].value_counts()

 0    2311
 1    1086
-1     574
 2      13
 4       9
 3       6
Name: cluser_id, dtype: int64

In [32]:
# grouping clusters using clustersid
airlines2.groupby('cluser_id').agg(['mean'])

Balance   Qual_miles cc1_miles cc2_miles cc3_miles  \
                    mean         mean      mean      mean      mean   
cluser_id                                                             
-1         181742.540070   931.761324  2.724739  1.057491  1.085366   
 0          53181.803548     3.660320  1.655993  1.000000  1.000000   
 1          60939.351750     9.894107  2.593923  1.000000  1.000000   
 2          34806.538462     0.000000  1.000000  2.000000  1.000000   
 3          38616.166667     0.000000  1.000000  3.000000  1.000000   
 4          27113.888889  2475.444444  1.000000  1.000000  1.000000   

            Bonus_miles Bonus_trans Flight_miles_12mo Flight_trans_12  \
                   mean        mean              mean            mean   
cluser_id                                                               
-1         39466.153310   22.055749       2172.263066        6.273519   
 0          9010.212462    8.451752        125.327131        0.401558   
 1         22898.413444   12.820442        278.409761        0.882136   
 2          8389.769231   12.000000         19.230769        0.153846   
 3         14966.833333   14.000000         41.666667        0.166667   
 4          2169.111111    4.555556         44.444444        0.333333   

          Days_since_enroll    Award?  
                       mean      mean  
cluser_id                              
-1              4742.745645  0.688153  
 0              3796.382518  0.000000  
 1              4505.348066  1.000000  
 2              3186.153846  0.000000  
 3              3835.666667  0.000000  
 4              1900.111111  0.000000